import { Comment, User } from '@prisma/client';

// Generated by https://quicktype.io
export interface Post {
  id: string;
  title: string;
  published: boolean;
  createdAt: Date;
  updatedAt: Date;
  authorId: string;
  author: Author;
  comments: Comment[];
}

interface Author {
  id: string;
  name: string;
  email: string;
  emailVerified: null;
  image: string;
}

export type PostDetailType = Post & {
  comments: (Comment & {
    author: User;
  })[];
  author: User;
};
